### ISSUE TITLE
Installation via Homebrew

### ISSUE THREAD

**Issue by athieriot** [glejeune/vf#1]
Hi,

   I see that vf is available with manual installation only. 
   Are you interested in an homebrew formulae? 

   If so, can I have you're authorization to do it myself? (trying to...)

Aurélien

**Comment by glejeune** [comment]
Hi

I'm working on an install script... But if you want to do it and make it compatible with homebrew, it's ok for me !

Thanks

Greg

**Comment by athieriot** [comment]
For now I've just plan to make homebrew copy files in the Cellar and tell user to add the "source vf.sh" command in their .(wathever).rc

What do you have in mind exactly?
Some ruby script who pull github or something more ?

Aurélien

**Comment by athieriot** [comment]
What do you think of that : https://github.com/athieriot/homebrew/commit/1d37189e2d3bff9b3fa90856a43c39979cdbd934 ?

**Comment by glejeune** [comment]
That's cool !!!

Thanks

**Comment by athieriot** [comment]
I'll ask a Pull Request to Homebrew master if you're ok. That's sound not very hard to be accepted. 
Unless you want to cherry pick that in you're proper fork.

**Comment by glejeune** [comment]
That's ok for me! Go!

**Comment by adamv** [comment]
vf is in Homebrew, this can be closed.

**Comment by jasonsyoung** [comment]
Not sure if this was just for me, but vf fails recently, I had to change `export VF_HOME=$(dirname $0)` to `export VF_HOME=$(brew --prefix vf)`
